### ISSUE TITLE
Weird output for the Video Network module

### ISSUE THREAD

**Issue by cardinot** [bernorieder/YouTube-Data-Tools#1]
I tried to use the video network module starting from a list of 100 video ids. I might be wrong, but since YouTube shows 20 related videos (not sure if we get the same amount of videos on the YouTube Data API), it should be crawling about 100 *20 * 20 * 20 (~800k) videos for a depth 2, but I got 6662 only.

I guess that many videos would be the same and that would be the reason why I should always get something much smaller than 800k...

I know 100 seeds is too much, but I'm wondering what's happening in this case!

log (without counting):
> getting details for 100 videos at depth 0: ...
> getting details for 467 videos at depth 1: ...
> getting related videos for 467 videos at depth 1: ...
> getting details for 6662 videos at depth 2: ...
> getting related videos for 6662 videos at depth 2: ...
> The script has created a net with 7226 channels from 100 seeds.

**Comment by ErikBorra** [comment]
Have you considered that not all videos might have 20 related videos?

**Comment by cardinot** [comment]
Hi Erik, many thanks for your reply.

> Have you considered that not all videos might have 20 related videos?

Actually it's true for YouTube. Whatever video that I open, it'll always show 20 videos on the "related videos" column. But yeah, it might be true for the YouTube Data API, where some videos could also be related to even more than 20 videos.

I didn't find any reference (or rough idea) about how it works, any thought?

**Comment by ErikBorra** [comment]
Not sure, but you can test the call made on [this line](https://github.com/bernorieder/YouTube-Data-Tools/blob/master/mod_videos_net.php#L287) manually.

**Comment by cardinot** [comment]
> Not sure, but you can test the call made on this line manually.

Yeah, I tried it a few hours ago ... but nothing really conclusive at all. =/
The amount of related videos varies a lot (I haven't found one with less than 20 - but I think it could happen)!

**Comment by ErikBorra** [comment]
What about running the code yourself and adding the following on [line 294](https://github.com/bernorieder/YouTube-Data-Tools/blob/master/mod_videos_net.php#L294):
```
print "<br>\n".count($reply->items)."\t - \t".$restquery." <br>\n";
```
This way you'll see which query resulted in how many related videos.

**Comment by cardinot** [comment]
Thanks Erik!

Actually it's possible to get the total results at once with
```php
$reply->pageInfo->totalResults
```
I did a few experiments, storing the total results of each video and counting how many of them are new ones...

As it might be useful for others, I will share my results here!

Starting from 390 seeds, hypothetically, in case of getting 20 different related videos for each seed, on the depth 1 we would have 390 + 390 * 20 = 8,190 videos.

How many did I get? 1,200 videos.
Seeds: 390 videos
Depth1: 810 videos

Total of related videos found from these 1,200 videos: 81,672
Average: 68.12 related videos
Max: 195 related videos
Min: 20 related videos

Conclusions:
- a video will always have other 20 related videos at least;
- depth 1 isn't so far away, so the videos may have most 'related videos' in common and that's fine;
- the YTDT output is correct.

**Comment by bernorieder** [comment]
only saw this now, thanks for the testing!
