### ISSUE TITLE
Weight of links in co-commenting networks

### ISSUE THREAD

**Issue by bkotras13** [bernorieder/YouTube-Data-Tools#11]
Hello,

I would like to know the number of shared commentators between 2 videos in the Co-Commenting Network Module. 

In Gephi's data laboratory, the link table shows a weight attribute as an integer, is it the litteral transcription of this number? For example, let's say this link has a "weight" of 39.0, does it mean that there are 39 people who commented on both videos?

Thank you so much for your help.

Baptiste

**Comment by bernorieder** [comment]
yes!

**Comment by bkotras13** [comment]
Thank you very much!
