### ISSUE TITLE
GDPR conformity

### ISSUE THREAD

**Issue by bkotras13** [bernorieder/YouTube-Data-Tools#12]
Dear colleagues of DMI,

I am part of a French national research project and I am asked to abide by GDPR, notably regarding the collection of comments. I am told that there are two options to do it legally:
1) Obtaining the consent of all individual users, which does not seem feasible
2) Obtaining the consent of the platform, which seems the way to go.

Has YouTube/Alphabet issued such a document, and would it cover a French research program? Is it possible to obtain a copy? 

With many thanks, both for your response and for maintaining such a great research tool.

Baptiste Kotras
LISIS / INRAE

**Comment by bernorieder** [comment]
Hi Baptiste,
I only saw your comment now, apologies. I imagine that you are speaking about our publicly accessible YTDT installation, and not the software package. Our API access is regularly vetted by YouTube and our API use follows the ToS. If you are unsure about the legal status of the public installation, I recommend applying for your own API key at https://research.youtube.com and install an instance of YTDT on one of your servers.

**Comment by bkotras13** [comment]
Hi Bernhard,
Thank you very much for your response. I was indeed talking about the public interface of YTDT.
I think that the fact that YouTube regularly approves YTDT is legally satisfying for my interlocutors. Is there a public document attesting such an approval, for me to prove it to my legal interlocutors?
Thank you,
Baptiste
