### ISSUE TITLE
Video List mod with a certain channel id doesnt scrape all videos of the channel

### ISSUE THREAD

**Issue by maxpi99** [bernorieder/YouTube-Data-Tools#13]
I noticed that for large channels with more than 20k videos the video list mod (with the channel id to make a video list) only returns the newest 20k videos. For example with the channel id "UC7fWeaHhqgM4Ry-RMpM2YYw" the channel info tool shows me a video count of 53723, while the video list only scrapes around 19k videos. My question/suggestion therefore would be if it would be possible for the video list module to select a time frame also for the channel ids and not only for the search query.
![grafik](https://github.com/bernorieder/YouTube-Data-Tools/assets/98280131/6ef3627f-7b62-417f-8f7f-478535d6c90b)
![grafik](https://github.com/bernorieder/YouTube-Data-Tools/assets/98280131/dab81db4-6139-4859-b545-38df0b039e0d)

**Comment by bernorieder** [comment]
The channel/list API endpoint unfortunately has not date parameter, so the max number of videos YouTube makes available is the max number we can get.

**Comment by maxpi99** [comment]
One possibility I tried to overcome this problem and which might be interesting is to use the search/list endpoint, which allows specifying the channel ID and a time frame. I used the yt_search function from the tuber R package (https://www.rdocumentation.org/packages/tuber/versions/0.9.9/topics/yt_search).

**Comment by bernorieder** [comment]
yes, that's a good idea! I'll have to test and see what the quota cost is to decide whether to integrate the approach into the YTDT
