### ISSUE TITLE
Can't call modules through the commandline, php only prints code and exits

### ISSUE THREAD

**Issue by dhsdshdhk** [bernorieder/YouTube-Data-Tools#4]
I'm trying to run this in my machine and I'm having some trouble getting it to work.
```

~/Downloads/YouTube-Data-Tools-master$ php mod_videos_net.php rankby=relevance mode=search iterations=2 crawldepth=1 query=yourquery filename=yourfilename

<!doctype html>

<html lang="en">
<head>
	<meta charset="utf-8">
	
	<title>YouTube Data Tools</title>
[...]
```

Do you know what I might be possibly doing wrong?

**Comment by ErikBorra** [comment]
Make sure you have installed php-cli. On Debian based systems you can install it via `sudo apt-get update; sudo apt-get install php7-cli` (if you have php7 installed)Op 18 jul. 2019 19:19 schreef dhsdshdhk <notifications@github.com>:I'm trying to run this in my machine and I'm having some trouble getting it to work.

~/Downloads/YouTube-Data-Tools-master$ php mod_videos_net.php rankby=relevance mode=search iterations=2 crawldepth=1 query=yourquery filename=yourfilename

<!doctype html>

<html lang="en">
<head>
	<meta charset="utf-8">
	
	<title>YouTube Data Tools</title>


Do you know what I might be possibly doing wrong?

**Comment by dhsdshdhk** [comment]
I already have it, @ErikBorra
`php7.2-cli is already the newest version (7.2.19-0ubuntu0.18.04.1).`

**Comment by bernorieder** [comment]
CLI has been improved, but still a bit of a work in progress.
