### ISSUE TITLE
Managing Captcha on personal server

### ISSUE THREAD

**Issue by gollivier** [bernorieder/YouTube-Data-Tools#5]
Hi, 

I'm trying to use YTDT on my own server to automatize longitudinal analysis. Nevertheless, when I test the tool on a WampServer on Windows (localhost), the captcha process returns me the following messages: "L'hôte local ne figure pas dans la liste des domaines acceptés pour la clé de ce site" ("the Localhost is not in the list of accepted domains for the key of this site"), and "Recaptcha missing". What could be the way to fix that?
Moreover, when using the php functions through command line, is the captcha a problem for automation?

Thanks in advance for any help

**Comment by bernorieder** [comment]
recaptcha parameter has been integrated into common.php
