### ISSUE TITLE
Video Network Module not working

### ISSUE THREAD

**Issue by nameuser3** [bernorieder/YouTube-Data-Tools#8]
URL of the call: https://tools.digitalmethods.net/netvizz/youtube/mod_videos_net.php
Browser: Firefox and Chrome

Output error message regardless of starting point: "The request failed. YouTube's API gave the following error: badRequest"

**Comment by EZgamertest** [comment]
same issue for me. Something with the API Request. tried downloading the files to figure it out but idk shit about php, especially not debugging. Issue maybe around line 360 of the code, or maybe something with YouTube's API itself I'm really not sure

**Comment by nameuser3** [comment]
Unfortunately, it's the API itself.

> August 7, 2023
As [announced on June 12, 2023](https://developers.google.com/youtube/v3/revision_history#release_notes_06_12_2023), the [search.list](https://developers.google.com/youtube/v3/docs/search/list) method's `relatedToVideoId` parameter has been deprecated. That parameter is no longer supported, and references to the parameter have been removed from the API documentation.

**Comment by bernorieder** [comment]
module has been removed

**Comment by bernorieder** [comment]
module has been removed after YT removed the API endpoint
