### ISSUE TITLE
YTDT site offline?

### ISSUE THREAD

**Issue by warren-pearce** [bernorieder/YouTube-Data-Tools#9]
https://tools.digitalmethods.net/netvizz/youtube/ no longer seems to be working since 27/10/23 - it is now redirecting to https://ytdt.digitalmethods.net/ (which may be new?) and I am receiving the error message in the attached screenshot. I am getting the same message on Firefox, Chrome and Safari (using Mac OS 12.6) 
<img width="945" alt="image" src="https://github.com/bernorieder/YouTube-Data-Tools/assets/55889221/a139fff4-d4c0-4392-9d50-7de63b9efb0d">

**Comment by bernorieder** [comment]
The tools has indeed moved to a new URL. Unfortunately, we are not able to guarantee 100% server uptime, if a tool does not work, try again in 24hrs, in most cases, things should be resolved by then.
